// IMPORT REQUIREMENTS
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';

// A list of dictionary to create the tasks on the todo application.
const DATA = [
  // { id: "todo-0", name: "Eat", completed: true },
  // { id: "todo-1", name: "Sleep", completed: false },
  // { id: "todo-2", name: "Repeat", completed: false }
];

// Render the document object model which is generated by react
ReactDOM.render(
  <React.StrictMode>
    <App tasks={DATA} />
  </React.StrictMode>,
  document.getElementById('root')
);
